### ISSUE TITLE
Mobile Money Processing

### ISSUE THREAD

**Issue by Serge-N** [ZambianTech/made-in-zambia#11]
As most of you are aware, we now have a new ministry of technology.

I won't list the challenges we are facing, as most of you already know them. Am sure most of you know that there is a missed 
opportunity in the mobile payment processing area.

We need a mobile processing API that is publicly available to both local and international developers. This API should :
-  be a paid for service.
-  should cover for all local mobile networks.
-  should be have SDK for at least five languages (i.e. Python, Java, Ruby ,Node and .NET) 

This would us to target more locals, hence  specialised software to meet the Zambian needs.

Currently, am not aware of any public , legal and proper API for money payment processing. If you know any , please list it here. A good example of where this would be extremely essential is local [stock trading](https://myluse.luse.co.zm/luse/wallet).

Just a thought, what do you think?

@dennism501
@chibaye
@Martin1998215
@Elbie-em
@IsaacHatilima
@Munsa1
@stctheproducer
@wbanda44
@chebwa
@elisha2kyakpo1
@DamianoSilverhand
@JamesrPrince
@LutLas
@Raphaelmbewe
@MadalitsoPhiri
@fderyckel
@Beardless-sheik
@DalitsoKasonde
@Kazion500
@justmvrco
@ikayz
@mmatongo
@ShadeB
@cazterk
@nmbazima
@alexdowad
@NickKatambo
@|rlyonheart
@chaiwa-berian
@chaw-bot
@StevenSanie
@Aypak
@csikasote
@engineervix
@Yakufaith
@elisha2kyakpo1
@Munalula-Sikazwe

I know all of you are busy people. But if really want to see change in the motherland. It's all up to you.

**Comment by Chizzoz** [comment]
@Serge-N I would say cGrate (543 / Konse Konse), Kazang and a few others are offering the API as you've described. The only thing missing is them also providing SDK's for different languages, which is where developers come in. Additionally, we are also in a better position now as you can integrate directly with Airtel and MTN with their OpenAPI offering and Zamtel is also accessible. Times have changed, things look good.

This is the time to grow beyond being techy or just focusing on development or at least having a diverse team if you can't handle all that. To get access to most of these API's, you need at least a business plan, some market research, planning, registered company, etc. With an entrepreneurial mindset, those things are at your fingertips.

**Comment by engineervix** [comment]
Thanks @Serge-N for bringing this up, I totally I agree with you. Integrating Payments in your app should not be a big issue, yet in Zambia it is. I don't know any  home grown, publicly available API. **Zynle Technologies** have an API, but you have to go to them, fill in forms, provide documents, sign some agreements ... it's a long process. The only "easy" option I know is using **Flutterwave**, which is from Nigeria, but has expanded across the African continent.

We really do need a home grown solution, something like *Stripe* but for Zambia and built by Zambians!

**Comment by Serge-N** [comment]
@Chizzoz Is it publicly available, online for devs to register?

**Comment by Chizzoz** [comment]
For MTN and Airtel you can register on their websites, Konse Konse too. But of course, you can't go into production or go-live after just registering online. I guess those guys hands are tied due to regulation around doing business and consumer protection. Which is where things like KYC, TPIN registration, business bank account, PACRA, etc come in.

**Comment by Raphaelmbewe** [comment]
@Serge-N This is a good idea however why will people prefer using this product to already existing ones which have already matured and competing out there?.

**Comment by Serge-N** [comment]
@Raphaelmbewe Its not about reinventing the wheel. It is about public availability, simplicity, and locality (optional).

**Comment by Raphaelmbewe** [comment]
@Serge-N great this is awesome

**Comment by engineervix** [comment]
> For MTN and Airtel you can register on their websites, Konse Konse too. But of course, you can't go into production or go-live after just registering online. I guess those guys hands are tied due to regulation around doing business and consumer protection. Which is where things like KYC, TPIN registration, business bank account, PACRA, etc come in.

This is the issue I have with the existing solutions, you have to go through so many (manual) steps to **actually** get to use these APIs. Documentation is also not so good. In a nutshell, they aren't as "developer friendly" as other APIs that we've all used. While it's understandable that regulations regarding KYC, Tax, Banking, etc have to be followed, such processes can (and should) be streamlined to make life easier for everyone, so that in no time I'm all set and ready to roll.

**Comment by engineervix** [comment]
> @Serge-N This is a good idea however why will people prefer using this product to already existing ones which have already matured and competing out there?.

- Wider language support
- better docs
- streamlined onboarding process

**Comment by Chizzoz** [comment]
@engineervix I think we can all agree that we have noticed a gap and that points to an opportunity.

My last thoughts on this matter are that; we have direct access to the actual service providers and some third-party providers, provided we meet their requirements with some administration stuff. There are a lot of opportunities that have presented themselves in the form of the launching of the National Financial Switch (NFS), Bank of Zambia (BOZ) and Security Exchange Commission (SEC) Regulatory Sandboxes, Financial Sector Deepening Zambia (FSDZ) workshops, FinTech Challenges/ Hackathons by BongoHive and others, etc.

The convenient API's and SDK's we say are missing here were developed by individuals and startups in other countries addressing a need and creating a business. Those services make easier on-boarding for their users because the service provider did the admin stuff. It's up to you to make a local PayPal, Stripe, Square, Braintree, Coinbase, etc.

**Comment by dennism501** [comment]
Outside the tech itself, we also need to look at the legal requirements that BoZ requires for one to be able to create a payment platform. It's a very tedious and long process just to be registered as a money mover or a fintech in Zambia. 
So that also discourages small local companies to set up shop and it's easier to bootstrap bigger companies and leverage their products. 

Also, getting on the NFS (I might be wrong, please correct me) requires a company to pay a once-off fee of $10,000 and you won't be charged any transactions fees for all transactions that go through. So for me, the tech isn't really the big blocker, it's regulation. 

Then we come to Card payments, being PCI DSS compliant is very expensive and the security requirements that are needed are also very strict. So have level 1 compliance, you need to pay about $50,000 annually for you to be able to do over 6,000,000 transactions in a year. 

So for me, there are a lot of hurdles to jump through for you to even think of starting a payment provider. It would need serious investment in both finances and human resources.

**Comment by Chizzoz** [comment]
Well put @dennism501, that's just the reality. Even Flutterwave for example, to get to where they're at, had to tackle those hurdles. You just can't register on https://developer.visa.com/ and get access to their card user base. You have to meet their requirements, they have a reputation to uphold.

NFS has rates for commercial banks and for FinTechs / MNO's with Designated Payment Systems License. Last time I checked, for commercial banks it was about $95,000 and FinTechs was about K20,000 to get onto NFS. For Designated Payment Systems, application fee should be about K500. You can find the list of companies and requirements here: https://www.boz.zm/designated-payment-system-institutions.htm 

Big ups to Ekamo, https://ekamo.co.zm/ they managed to find themselves there. That's inspiring!

The beauty with the times we are living in, you are able to achieve even Level 1 PCI DSS Compliance with cloud hosting PaaS platforms, of course at a cost.

For quick eCommerce or monetization options, with little admin, you might want to get on-boarded onto services that have already done the heavy lifting for you; like Flutterwave, Shopify, WooCommerce, Wix, etc. See how that goes, then hopefully scale up to more direct integration.

**Comment by engineervix** [comment]
Thanks @Chizzoz and @dennism501 for the great insights.

**Comment by dennism501** [comment]
I didn't know that the rates for NFS were like that. I think for me we should look at building new products as opposed to making the "Zambian" version of already existing products. I will give an example of Zazu, they have leveraged existing products and put them together to make their product find product-market fit and that helps you reach the market quicker. 

As much it would be nice to have a local payment provider like Flutterwave, most of us don't have the resources they do in Nigeria and the other parts of Africa. So building solutions that will solve a lot of people in the payment industry. Like if we create a local payment system, what problem are we going to be solving? But there are other problems that we haven't solved yet like a proper checkout platform for e-commerce in Zambia like what Paystack is doing with their [Paystack store front](https://paystack.com/storefront/). There is so much we can do to make payments easier for the average consumer. 

There are so many problems I would like to tackle and there is so much more. I recently learnt that [TransferWise](https://wise.com/) use Flutterwave rails to make their cross-boarder payments. So that's an example of how we can build products based off the already existing products. The fact I keep making reference to Flutterwave lol is because they have done amazing work in their space and have enabled us to do so many things.

**Comment by Serge-N** [comment]
I guess we just have to push for better docs and more SDKs.

**Comment by stctheproducer** [comment]
> I guess we just have to push for better docs and more SDKs.

In that case, we'll need:

1. An open-source repo for each language-specific SDK so that we leverage the experience of multiple devs.
2. Each repo can consult someone who has access to the sandbox accounts, if any.
3. Documentation for each SDK.

**Comment by nmbazima** [comment]
Good day Serge and All,
Thanks for reaching out. This is quite interesting, we would need to
get on a platform to collaborate for those interested or who just want
to know what is happening.

Maybe slack or create a repositoryfor everyone to contribute to.
-- 
Kindest regards
Newton Mukuka Mbazima
Email: ***@***.***
https://www.linkedin.com/in/nmbazima/
Cell:  +260 974 778 611 | +260 966 697 356
Work: +260 968 492 492
--
Sent on Evolution mail client
@dennism501
@chibaye
@Martin1998215
@Elbie-em
@IsaacHatilima
@Munsa1
@stctheproducer
@wbanda44
@chebwa
@elisha2kyakpo1
@DamianoSilverhand
@JamesrPrince
@LutLas
@Raphaelmbewe
@MadalitsoPhiri
@fderyckel
@Beardless-sheik
@DalitsoKasonde
@Kazion500
@justmvrco
@ikayz
@mmatongo
@ShadeB
@cazterk
@nmbazima
@alexdowad
@NickKatambo
@|rlyonheart
@chaiwa-berian
@chaw-bot
@StevenSanie
@Aypak
@csikasote
@engineervix
@Yakufaith
@elisha2kyakpo1
@Munalula-Sikazwe

-----Original Message-----
From: Serge Nalishiwa ***@***.***>
Reply-To: ZambianTech/made-in-zambia
***@***.***>
To: ZambianTech/made-in-zambia ***@***.***>
Cc: Newton Mbazima ***@***.***>, Mention
***@***.***>
Subject: [ZambianTech/made-in-zambia] Mobile Money Processing (#11)
Date: Mon, 13 Sep 2021 11:55:41 -0700

As most of you are aware, we now have a new ministry of technology.
I won't list the challenges we are facing, as most of you already know
them. Am sure most of you know that there is a missed
opportunity in the mobile payment processing area.
We need a mobile processing API that is publicly available to both
local and international developers. This API should :
 * be a paid for service.
 * should cover for all local mobile networks.
 * should be have SDK for at least five languages (i.e. Python, Java,
   Ruby ,Node and .NET)
This would us to target more locals, hence specialised software to meet
the Zambian needs.
Currently, am not aware of any public , legal and proper API for money
payment processing. If you know any , please list it here. A good
example of where this would be extremely essential is local stock
trading.
Just a thought, what do you think?
@dennism501
@chibaye
@Martin1998215
@Elbie-em
@IsaacHatilima
@Munsa1
@stctheproducer
@wbanda44
@chebwa
@elisha2kyakpo1
@DamianoSilverhand
@JamesrPrince
@LutLas
@Raphaelmbewe
@MadalitsoPhiri
@fderyckel
@Beardless-sheik
@DalitsoKasonde
@Kazion500
@justmvrco
@ikayz
@mmatongo
@ShadeB
@cazterk
@nmbazima
@alexdowad
@NickKatambo
@|rlyonheart
@chaiwa-berian
@chaw-bot
@StevenSanie
@Aypak
@csikasote
@engineervix
@Yakufaith
@elisha2kyakpo1
@Munalula-Sikazwe
I know all of you are busy people. But if really want to see change in
the motherland. It's all up to you.

**Comment by Beardless-sheik** [comment]
Yeah. It would be great if someone started a slack/ discord chat maybe to discuss it further for those interested! Pretty sure the chat will be more fruitful over there than on here........

**Comment by justmvrco** [comment]
slack chat will work

**Comment by chaiwa-berian** [comment]
@Serge-N @nmbazima Lets keep this thread going. Would you kindly start a repo? Ideas should not just die, we have to learn to give everything a shot! All the great products we see around are, for the most part, as a result of "re-inventing the wheel"!  :smile:

**Comment by Serge-N** [comment]
We had a discussion with airtel, a week ago. There are saying that their API is still in staging.

Any of using it in beta for production?

Airtel did not really give us a date as to when their API will be fully available.

**Comment by chaiwa-berian** [comment]
Can we start with what is available? I guess MoMo is?

**Comment by Serge-N** [comment]
Any links for Momo?

**Comment by chaiwa-berian** [comment]
> Any links for Momo?

https://momodeveloper.mtn.com/

**Comment by mu-chi-ha** [comment]
Hey Guys! New to the party here and encountered the same challenge. This is a very insightful thread. How far did you go with this?

**Comment by Serge-N** [comment]
@mu-chi-ha I will go to Airtel and ask for you (this week), as is, they haven't been responding to emails.

The requirements for both staging and production are also not clear. 

Another issue is our API's, on the Zambian part as seen from the developer portal, are lagging. 

Anyone with experience in this area, please help your fellow developer.

**Comment by Serge-N** [comment]
Here are the results so far.

<img width="886" alt="image" src="https://github.com/ZambianTech/made-in-zambia/assets/51508252/586e7135-5b65-4fa0-8651-c397df4e632f">

Step 1 is easy. Step 2 and 3 will require you to contact Airtel. Support on the developer portal does not work. The need to contact Airtel will be so that you get the client key for testing.

Step 3: The requirements for Compliance required for Production are not published by the Portal and they are not given in public. You will still need to contact Airtel to find out what these are for your use case.

 I was told in person by Customer support, that they have to see everything you are building so that they can decide if they want to work with you.

To contact Airtel concerning the developer portal. Contact Mr. Chibale via the following email:

![contact](https://github.com/ZambianTech/made-in-zambia/assets/51508252/3c17979b-e54c-4ccb-9de9-3a31635c66a2)

Please note that I have not made the number public because I don't know if it's a work or personal number.
 
Gate keeping or security requirements, you get to decide that on your own.

[@dennism501](https://github.com/dennism501)
[@chibaye](https://github.com/chibaye)
[@Martin1998215](https://github.com/Martin1998215)
[@Elbie-em](https://github.com/Elbie-em)
[@IsaacHatilima](https://github.com/IsaacHatilima)
[@Munsa1](https://github.com/Munsa1)
[@stctheproducer](https://github.com/stctheproducer)
[@wbanda44](https://github.com/wbanda44)
[@chebwa](https://github.com/chebwa)
[@elisha2kyakpo1](https://github.com/elisha2kyakpo1)
[@DamianoSilverhand](https://github.com/DamianoSilverhand)
[@JamesrPrince](https://github.com/JamesrPrince)
[@LutLas](https://github.com/LutLas)
[@Raphaelmbewe](https://github.com/Raphaelmbewe)
[@MadalitsoPhiri](https://github.com/MadalitsoPhiri)
[@fderyckel](https://github.com/fderyckel)
[@Beardless-sheik](https://github.com/Beardless-sheik)
[@DalitsoKasonde](https://github.com/DalitsoKasonde)
@Kazion500
[@justmvrco](https://github.com/justmvrco)
[@ikayz](https://github.com/ikayz)
[@mmatongo](https://github.com/mmatongo)
[@ShadeB](https://github.com/ShadeB)
[@cazterk](https://github.com/cazterk)
[@nmbazima](https://github.com/nmbazima)
[@alexdowad](https://github.com/alexdowad)
[@NickKatambo](https://github.com/NickKatambo)
@|rlyonheart
[@chaiwa-berian](https://github.com/chaiwa-berian)
[@chaw-bot](https://github.com/chaw-bot)
[@StevenSanie](https://github.com/StevenSanie)
[@Aypak](https://github.com/Aypak)
[@csikasote](https://github.com/csikasote)
[@engineervix](https://github.com/engineervix)
@Yakufaith
[@elisha2kyakpo1](https://github.com/elisha2kyakpo1)
[@Munalula-Sikazwe](https://github.com/Munalula-Sikazwe)
[@dennism501](https://github.com/dennism501)
[@chibaye](https://github.com/chibaye)
[@Martin1998215](https://github.com/Martin1998215)
[@Elbie-em](https://github.com/Elbie-em)
[@IsaacHatilima](https://github.com/IsaacHatilima)
[@Munsa1](https://github.com/Munsa1)
[@stctheproducer](https://github.com/stctheproducer)
[@wbanda44](https://github.com/wbanda44)
[@chebwa](https://github.com/chebwa)
[@elisha2kyakpo1](https://github.com/elisha2kyakpo1)
[@DamianoSilverhand](https://github.com/DamianoSilverhand)
[@JamesrPrince](https://github.com/JamesrPrince)
[@LutLas](https://github.com/LutLas)
[@Raphaelmbewe](https://github.com/Raphaelmbewe)
[@MadalitsoPhiri](https://github.com/MadalitsoPhiri)
[@fderyckel](https://github.com/fderyckel)
[@Beardless-sheik](https://github.com/Beardless-sheik)
[@DalitsoKasonde](https://github.com/DalitsoKasonde)
@Kazion500
[@justmvrco](https://github.com/justmvrco)
[@ikayz](https://github.com/ikayz)
[@mmatongo](https://github.com/mmatongo)
[@ShadeB](https://github.com/ShadeB)
[@cazterk](https://github.com/cazterk)
[@nmbazima](https://github.com/nmbazima)
[@alexdowad](https://github.com/alexdowad)
[@NickKatambo](https://github.com/NickKatambo)
@|rlyonheart
[@chaiwa-berian](https://github.com/chaiwa-berian)
[@chaw-bot](https://github.com/chaw-bot)
[@StevenSanie](https://github.com/StevenSanie)
[@Aypak](https://github.com/Aypak)
[@csikasote](https://github.com/csikasote)
[@engineervix](https://github.com/engineervix)
@Yakufaith
[@elisha2kyakpo1](https://github.com/elisha2kyakpo1)
[@Munalula-Sikazwe](https://github.com/Munalula-Sikazwe)
@mu-chi-ha

**Comment by mu-chi-ha** [comment]
Hello Serge.

Thank you very much for the info. This is very valuable, and i will proceed
as guided!

Kind regards.
